# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cli_pcart <- function(rdata, predictorCount, dataCount, pred_catCounts, res_type, res_catCount, alpha = 0.5, kappa = 0.25, ess = 1.0, useStructureScore = TRUE) {
    .Call(`_rpcart_cli_pcart`, rdata, predictorCount, dataCount, pred_catCounts, res_type, res_catCount, alpha, kappa, ess, useStructureScore)
}

